#!/usr/bin/env php
<?php
$subjects_scan=scandir(__DIR__."/src/subjects");
$templates_scan=scandir(__DIR__."/src/testsuite/templates");
$auto_scan=scandir(__DIR__."/src/testsuite/tests/auto");
$templates=[];
foreach($templates_scan as $fname)
{
  if($fname[0]==".")continue;
  $templates[$fname=file_get_contents(__DIR__."/src/testsuite/templates/$fname");
}
foreach($auto_scan as $fname)
{
  if($fname[0]==".")continue;
  unlink(__DIR__."/src/testsuite/tests/auto/$fname");
}
foreach($subjects_scan as $file)
{
  $conts=file_get_contents(__DIR__."/src/subjects/$file");
  if(strpos($conts,"extends DreamCreature")!==false)
  {
    $creature=explode(".as",$file)[0];
    $owner=explode("\"",explode("owner=Subjects.SUBJECT_OBJECTS[Subjects.SUBJECT_NAMES.indexOf(\"",$conts)[1])[0];
    foreach($templates as $test=>$template)
    {
      file_put_contents(__DIR__."/src/testsuite/tests/auto/Test$test".ucfirst($creature).".as",str_replace("%PARSEDCREATURE%",handleParsed($creature),str_replace("%LCCREATURE%",strtolower($creature),str_replace("%UCCREATURE%",strtoupper(handleUS($creature)),str_replace("%OWNER%",strtolower($owner),str_replace("%OWNER_GENDER%",(strtolower($owner)=="edyn")?("She"):("He"),str_replace("%UCOWNER%",ucfirst(strtolower($owner)),str_replace("%UCFIRSTCREATURE%",$creature,$template))))))));
      //file_put_contents(__DIR__."/src/testsuite/AllTests.as",file_get_contents(__DIR__."/src/tests/AllTests.as")."\naddTest(new Test$test".ucfirst($creature)."());");
    }
  }
}
function handleUS($creature)
{
  if(ucfirst(strtolower($creature))==$creature)
  {
    return strtoupper($creature);
  }
  $return_string=$creature[0];
  for($i=1;$i<strlen($creature);$i++)
  {
    if($creature[$i]==strtoupper($creature[$i]))
    {
      $return_string.="_";
    }
    $return_string.=$creature[$i];
  }
  return strtoupper($return_string);
}
function handleParsed($creature)
{
  if(ucfirst(strtolower($creature))==$creature)
  {
    return ucfirst(strtolower($creature));
  }
  $return_string=$creature[0];
  for($i=1;$i<strlen($creature);$i++)
  {
    if($creature[$i]==strtoupper($creature[$i]))
    {
      $return_string.=" ";
    }
    $return_string.=$creature[$i];
  }
  return ucwords(strtolower($return_string));
}
